export const TOGGLE_VIM = "toggle_vim"
export const SET_SUGGESTION = "set_suggestion"
export const VIM_COMMAND = "vim_command"
export const LOAD_SUGGESTION = "load_suggestion"
export const EMPTY_SUGGESTION = "empty_suggestion"
export const SET_TITLE = "set_title"
export const CHANGE_TAB = "change_tab"